"""
PolicyGuard-AI: GitHub Service
Auto-generates Pull Requests with new Guardrail code changes,
enabling human-in-the-loop review before production deployment.
"""
import os
import base64
import datetime
from typing import Dict, Optional

try:
    from github import Github, GithubException
    HAS_GITHUB = True
except ImportError:
    HAS_GITHUB = False


class GithubService:
    """
    Creates branches, commits guardrail code, and opens Draft PRs
    using the PyGithub library and a personal access token.
    """

    def __init__(self):
        self.token = os.getenv("GITHUB_TOKEN", "")
        self.repo_name = os.getenv("GITHUB_REPO", "")  # e.g. "shalcoder/PolicyGuard-AI"
        self._client = None
        self._repo = None

        if not HAS_GITHUB:
            print("[GitHub] PyGithub not installed. PR generation disabled.")
            return

        if not self.token or not self.repo_name:
            print("[GitHub] GITHUB_TOKEN or GITHUB_REPO not set. PR generation disabled.")
            return

        try:
            self._client = Github(self.token)
            self._repo = self._client.get_repo(self.repo_name)
            print(f"[GitHub] Connected to repo: {self.repo_name}")
        except Exception as e:
            print(f"[GitHub] Connection failed: {e}")

    def is_available(self) -> bool:
        return self._repo is not None

    def create_guardrail_pr(
        self,
        guardrail_code: str,
        violation_summary: str,
        language: str = "python",
        healing_id: str = "auto"
    ) -> Dict:
        """
        Creates a new branch, commits the guardrail code,
        and opens a Draft PR for human review.

        Returns a dict with `pr_url`, `branch`, `status`.
        """
        if not self.is_available():
            return {
                "status": "skipped",
                "reason": "GitHub integration not configured. Set GITHUB_TOKEN and GITHUB_REPO env vars.",
                "pr_url": None
            }

        timestamp = datetime.datetime.utcnow().strftime("%Y%m%d-%H%M%S")
        branch_name = f"policyguard/fix-{timestamp}"
        ext = "py" if language.lower() == "python" else "java" if language.lower() == "java" else "ts"
        file_path = f"backend/guardrails/auto_generated_{timestamp}.{ext}"

        try:
            # Get SHA of main branch
            main_ref = self._repo.get_git_ref("heads/main")
            main_sha = main_ref.object.sha

            # Create new branch
            self._repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=main_sha)

            # Create the file in the new branch
            commit_message = f"🛡️ PolicyGuard Auto-Patch [{healing_id}]\n\nViolations addressed:\n{violation_summary[:500]}"
            self._repo.create_file(
                path=file_path,
                message=commit_message,
                content=guardrail_code,
                branch=branch_name
            )

            # Create Draft PR
            pr = self._repo.create_pull(
                title=f"🛡️ PolicyGuard Guardrail Patch [{healing_id}]",
                body=self._build_pr_body(violation_summary, healing_id, language),
                head=branch_name,
                base="main",
                draft=True
            )

            return {
                "status": "success",
                "pr_url": pr.html_url,
                "pr_number": pr.number,
                "branch": branch_name,
                "file_path": file_path
            }

        except Exception as e:
            return {
                "status": "error",
                "reason": str(e),
                "pr_url": None
            }

    def _build_pr_body(self, violation_summary: str, healing_id: str, language: str) -> str:
        return f"""## 🛡️ PolicyGuard Autonomous Guardrail Patch

**Healing ID**: `{healing_id}`
**Language**: `{language}`
**Generated by**: PolicyGuard AI Self-Healing Engine

---

### Violations Addressed
```
{violation_summary}
```

---

### Review Checklist
- [ ] Code does not introduce new dependencies
- [ ] Logic correctly addresses all listed violations
- [ ] Existing test suite passes
- [ ] No sensitive data is hardcoded

> ⚠️ This is a **Draft PR** auto-generated by PolicyGuard. 
> A human administrator must approve and merge this patch.
> Do NOT merge unless you have reviewed the code thoroughly.
"""


# Global instance
github_service = GithubService()
