from fpdf import FPDF
from io import BytesIO
import datetime

class PDFReport(FPDF):
    def header(self):
        # Logo placeholder or simple text
        self.set_font("Arial", "B", 16)
        self.cell(0, 10, "PolicyGuard AI - Compliance Certificate", 0, 1, "C")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} - Generated by PolicyGuard AI", 0, 0, "C")

class PDFGenerator:
    def create_compliance_certificate(self, report_data: dict) -> bytes:
        pdf = PDFReport()
        pdf.alias_nb_pages()
        pdf.add_page()
        
        # --- Title Section ---
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 10, f"Evaluation ID: {datetime.datetime.now().strftime('%Y%m%d-%H%M%S')}", 0, 1)
        pdf.set_font("Arial", "", 10)
        pdf.cell(0, 10, f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1)
        pdf.ln(5)

        report = report_data.get("report", {})
        spec = report.get("system_spec", {})
        risk = report.get("risk_assessment", {})
        biz = report.get('business_impact', {})
        verdict = report.get("verdict", {})

        # --- Executive Summary ---
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "Executive Summary", 0, 1)
        pdf.set_fill_color(240, 240, 240)
        pdf.rect(10, pdf.get_y(), 190, 40, 'F')
        
        pdf.set_font("Arial", "B", 10)
        pdf.cell(40, 10, "System Name:", 0, 0)
        pdf.set_font("Arial", "", 10)
        pdf.cell(0, 10, spec.get("primary_purpose", "N/A")[:60], 0, 1)
        
        pdf.set_font("Arial", "B", 10)
        pdf.cell(40, 10, "Verdict:", 0, 0)
        
        status_color = (200, 50, 50) if verdict.get("approved") is False else (50, 150, 50)
        pdf.set_text_color(*status_color)
        pdf.cell(0, 10, verdict.get("status_label", "Unknown").upper(), 0, 1)
        pdf.set_text_color(0, 0, 0)

        pdf.set_font("Arial", "B", 10)
        pdf.cell(40, 10, "Overall Risk:", 0, 0)
        pdf.cell(0, 10, f"{risk.get('overall_rating', 'Unknown')} ({risk.get('overall_score', 0)}/100)", 0, 1)
        pdf.ln(15)

        # --- Business Impact ---
        if biz:
            pdf.set_font("Arial", "B", 14)
            pdf.cell(0, 10, "Business Impact Analysis", 0, 1)
            pdf.set_font("Arial", "", 10)
            
            data = [
                ("Financial Exposure", biz.get("financial_exposure", "-"), biz.get("estimated_cost", "-")),
                ("Regulatory Penalty", "High Risk" if "High" in biz.get("regulatory_penalty", "") else "Standard", biz.get("regulatory_penalty", "-")[:80]),
                ("Brand Reputation", biz.get("brand_reputation", "-")[:30], biz.get("brand_reputation", "-")),
            ]
            
            # Simple Table
            pdf.set_font("Arial", "B", 10)
            pdf.cell(50, 8, "Category", 1)
            pdf.cell(40, 8, "Level", 1)
            pdf.cell(100, 8, "Details", 1)
            pdf.ln()
            
            pdf.set_font("Arial", "", 10)
            for row in data:
                pdf.cell(50, 8, row[0], 1)
                pdf.cell(40, 8, row[1], 1)
                pdf.cell(100, 8, row[2], 1)
                pdf.ln()
            pdf.ln(10)

        # --- Policy Violations ---
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "Key Policy Violations", 0, 1)
        
        evidence = report.get("evidence", [])
        if not evidence:
            pdf.set_font("Arial", "I", 10)
            pdf.cell(0, 10, "No major violations detected.", 0, 1)
        else:
            for item in evidence:
                pdf.set_font("Arial", "B", 10)
                pdf.cell(0, 8, f"{item.get('severity', 'WARN')} - {item.get('policy_section', 'General')}", 0, 1)
                
                pdf.set_font("Arial", "", 9)
                pdf.multi_cell(0, 6, f"Issue: {item.get('issue_description', '')}")
                pdf.set_font("Courier", "", 8)
                pdf.multi_cell(0, 6, f"Snippet: \"{item.get('snippet', '')}\"")
                pdf.ln(3)

        # Output
        return bytes(pdf.output())
