from fpdf import FPDF
from io import BytesIO
import datetime

class PDFReport(FPDF):
    def header(self):
        # Logo placeholder or simple text
        self.set_font("Arial", "B", 16)
        self.cell(0, 10, "PolicyGuard AI - Compliance Certificate", 0, 1, "C")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} - Generated by PolicyGuard AI", 0, 0, "C")

class PDFGenerator:
    def create_compliance_certificate(self, report_data: dict) -> bytes:
        pdf = PDFReport()
        pdf.alias_nb_pages()
        pdf.add_page()
        
        # Helper to clean text for PDF (latin-1 only for core fonts)
        def clean_text(text):
            if text is None: return ""
            text = str(text)
            # Encode to latin-1, replacing errors with '?', then decode
            return text.encode('latin-1', 'replace').decode('latin-1')

        pdf.set_margins(10, 10, 10)
        pdf.set_auto_page_break(auto=True, margin=15)
        
        # --- Title Section ---
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 10, clean_text(f"Evaluation ID: {datetime.datetime.now().strftime('%Y%m%d-%H%M%S')}"), 0, 1)
        pdf.set_font("Arial", "", 10)
        pdf.cell(0, 10, clean_text(f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"), 0, 1)
        pdf.ln(5)

        report = report_data.get("report", {})
        spec = report.get("system_spec", {})
        risk = report.get("risk_assessment", {})
        biz = report.get('business_impact', {})
        verdict = report.get("verdict", {})

        # --- Executive Summary ---
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, clean_text("Executive Summary"), 0, 1)
        
        # Explicit width 190 = 210(A4) - 20(Margins)
        pdf.set_fill_color(240, 240, 240)
        pdf.rect(10, pdf.get_y(), 190, 40, 'F')
        
        pdf.set_font("Arial", "B", 10)
        pdf.cell(40, 10, clean_text("System Name:"), 0, 0)
        pdf.set_font("Arial", "", 10)
        pdf.cell(0, 10, clean_text(spec.get("primary_purpose", "N/A")[:60]), 0, 1)
        
        pdf.set_font("Arial", "B", 10)
        pdf.cell(40, 10, clean_text("Verdict:"), 0, 0)
        
        status_color = (200, 50, 50) if verdict.get("approved") is False else (50, 150, 50)
        pdf.set_text_color(*status_color)
        pdf.cell(0, 10, clean_text(verdict.get("status_label", "Unknown").upper()), 0, 1)
        pdf.set_text_color(0, 0, 0)

        pdf.set_font("Arial", "B", 10)
        pdf.cell(40, 10, clean_text("Overall Risk:"), 0, 0)
        pdf.cell(0, 10, clean_text(f"{risk.get('overall_rating', 'Unknown')} ({risk.get('overall_score', 0)}/100)"), 0, 1)
        pdf.ln(15)

        # --- Business Impact ---
        if biz:
            pdf.set_font("Arial", "B", 14)
            pdf.cell(0, 10, clean_text("Business Impact Analysis"), 0, 1)
            pdf.set_font("Arial", "", 10)
            
            # Helper to guess level from text
            def get_level(text):
                t = str(text).lower()
                if "high" in t or "severe" in t or "critical" in t: return "High"
                if "medium" in t or "moderate" in t: return "Medium"
                if "low" in t: return "Low"
                return "Info"

            data = [
                ("Financial Exposure", biz.get("financial_exposure", "-"), biz.get("estimated_cost", "-")),
                ("Regulatory Penalty", get_level(biz.get("regulatory_penalty", "")), str(biz.get("regulatory_penalty", "-"))[:100]),
                ("Brand Reputation", get_level(biz.get("brand_reputation", "")), str(biz.get("brand_reputation", "-"))[:100]),
            ]
            
            # Table: 50+30+110 = 190
            pdf.set_font("Arial", "B", 10)
            pdf.cell(50, 8, clean_text("Category"), 1)
            pdf.cell(30, 8, clean_text("Level"), 1)
            pdf.cell(0, 8, clean_text("Details"), 1) # Use remaining width
            pdf.ln()
            
            pdf.set_font("Arial", "", 10)
            for row in data:
                pdf.cell(50, 8, clean_text(row[0]), 1)
                pdf.cell(30, 8, clean_text(row[1]), 1)
                pdf.cell(0, 8, clean_text(row[2]), 1)
                pdf.ln()
            pdf.ln(10)

        # --- Policy Violations ---
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, clean_text("Key Policy Violations"), 0, 1)
        
        evidence = report.get("evidence", [])
        if not evidence:
            pdf.set_font("Arial", "I", 10)
            pdf.cell(0, 10, clean_text("No major violations detected."), 0, 1)
        else:
            for item in evidence:
                # Ensure X is reset to margin before writing block
                pdf.set_x(10)
                
                pdf.set_font("Arial", "B", 10)
                sev = clean_text(item.get('severity', 'WARN'))
                sect = clean_text(item.get('policy_section', 'General'))
                # Explicit width 190
                pdf.multi_cell(190, 6, f"{sev} - {sect}")
                
                pdf.set_font("Arial", "", 9)
                desc = clean_text(item.get('issue_description', ''))
                pdf.set_x(10) # FORCE RESET X
                pdf.multi_cell(190, 6, f"Issue: {desc}")
                
                pdf.set_font("Courier", "", 8)
                snip = clean_text(item.get('snippet', ''))
                pdf.set_x(10) # FORCE RESET X
                pdf.multi_cell(190, 6, f"Snippet: \"{snip}\"")
                pdf.ln(3)

        # Output
        # fpdf2 `output()` returns bytes/bytearray
        try:
            return bytes(pdf.output())
        except Exception as e:
            print(f"FAILED TO SERIALIZE PDF: {e}")
            raise e
